Entity class sms_requests added inside model package
AnsariMohsin1998/NotificationService pull request #1
Opened 2021-02-09 09:48 UTC by AnsariMohsin1998

2021-02-09 09:55 UTC, sachinkrmeesho requested changes

2021-02-09 09:55 UTC, sachinkrmeesho commented on src/main/java/com/meesho/mohsin/NotificationService/model/SmsRequests.java
> +    //  GETTERS AND SETTERS
no need of getter setter and constructor, data annotation will handle it

2021-02-09 09:56 UTC, AnsariMohsin1998 commented on src/main/java/com/meesho/mohsin/NotificationService/model/SmsRequests.java
> +    //  GETTERS AND SETTERS
okay 👍

2021-02-09 19:40 UTC, AnsariMohsin1998 commented
Made SmsController which calls SmsService which uses SmsRepository to fetch data from database

2021-02-10 07:21 UTC, sachinkrmeesho requested changes

2021-02-10 07:21 UTC, sachinkrmeesho commented on src/main/java/com/meesho/mohsin/NotificationService/controller/SmsController.java
> +public class SmsController {
add @RequestMapping("api/v1/sms") here

2021-02-10 07:21 UTC, sachinkrmeesho commented on src/main/java/com/meesho/mohsin/NotificationService/controller/SmsController.java
> +    @GetMapping(value = "/sms")
/get/bulk

2021-02-10 07:21 UTC, sachinkrmeesho commented on src/main/java/com/meesho/mohsin/NotificationService/controller/SmsController.java
> +    @GetMapping(value = "/sms/{id}")
/get/{id}

2021-02-10 07:21 UTC, sachinkrmeesho commented on src/main/java/com/meesho/mohsin/NotificationService/model/SmsRequests.java
> +
add preupdate here 
@PreUpdate
    public void preUpdate(){
        updated_at = new Date();
    }

2021-02-10 07:21 UTC, sachinkrmeesho commented on src/main/java/com/meesho/mohsin/NotificationService/model/SmsRequests.java
> +
it will automatically set updated_at date when we update any db entity

2021-02-10 07:21 UTC, sachinkrmeesho commented on src/main/java/com/meesho/mohsin/NotificationService/model/SmsRequests.java
> +    private int id;
use Integer not int... avoid using primitive in db entities

2021-02-10 07:21 UTC, sachinkrmeesho commented on src/main/java/com/meesho/mohsin/NotificationService/repository/SmsRepository.java
> +    SmsRequests findById(int id);  // why can't i use Long ?
use Integer

2021-02-10 07:21 UTC, sachinkrmeesho commented on src/main/java/com/meesho/mohsin/NotificationService/repository/SmsRepository.java
> +    SmsRequests findById(int id);  // why can't i use Long ?
you can not use long in place of integer as long to int conversion is not recommended

2021-02-10 07:21 UTC, sachinkrmeesho commented on src/main/java/com/meesho/mohsin/NotificationService/service/SmsService.java
> +    public SmsRequests findSmsRequestById(int id){
never return db entity from service class.. make a new Object like SmsGetResponse and initialize it will SmsRequests and then return,

2021-02-10 07:30 UTC, AnsariMohsin1998 commented
Thanks for all the suggestions , will update it ASAP.

2021-02-10 11:59 UTC, AnsariMohsin1998 commented
Updated .

2021-02-11 08:12 UTC, AnsariMohsin1998 commented
Added porper success and error response for v1/sms/send

2021-02-11 20:26 UTC, AnsariMohsin1998 commented
IMPLEMENTED

1) POST /v1/sms/send
2)POST /v1/blacklist
3)DELETE/V1/blacklist/{phone_number}
4)GET /v1/blacklist
5)GET /v1/sms/<request_id>

REMAINING
6)Get all sms sent to phone number between given start and end time (With Pagination) (Get from elastic search)
7)Get all sms containing given text (With Pagination) (Get from elastic search)

2021-02-12 08:28 UTC, AnsariMohsin1998 commented
ADDED KAFKA PRODUCER AND CONSUMER FUNCTIONALITY !

2021-02-15 07:58 UTC, AnsariMohsin1998 commented
Integrated 3rd party api.

2021-02-17 09:00 UTC, AnsariMohsin1998 commented
Added Elastic Search Functionality .

2021-02-19 07:30 UTC, AnsariMohsin1998 commented
ADDED RESPONSES AND DTO'S FOR ELASTIC SEARCH.

2021-02-22 16:12 UTC, AnsariMohsin1998 commented
Added authentication header.

2021-06-14 16:26 UTC, merged